services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: project_gestion_db
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: technique
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./project_gestion
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: project_gestion_db
      DB_USER: project_user
      DB_PASSWORD: technique
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./project_gestion:/app
    ports:
      - "8000:8000"
    command: sh ./scripts/entrypoint.sh

  front:
    build: ./front
    container_name: react_app
    restart: always
    depends_on:
      - web
    ports:
      - "3000:80"

volumes:
  postgres_data:
